- hosts: webserver
  tasks:
  - name: Setting-up Webserver
    package:
      name: "httpd"
      state: present

  - name: Setting-up Php
    package:
      name: "php"
      state: present

  - name: Copying file in server's ActiveDirectory
    copy:
      src: "index.php"
      dest: "/var/www/html/"

  - name: Starting Webserver
    service:
      name: "httpd"
      state: started

- hosts: Loadbalancer
  tasks:
  - name: Installing HA-proxy(LoadBalancer)
    package: 
      name: "haproxy"
      state: present

  - name : Configuring haproxy.cfg file
    template:
      src : "haproxy.cfg"
      dest: "/etc/haproxy/haproxy.cfg"
      
  - name : Starting Load-balancer services
    service:
      name: "haproxy"
      state: started
